version: '2'
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=veryhardpassword
      - MYSQL_DATABASE=easyapp
      - MYSQL_USER=easyapp
      - MYSQL_PASSWORD=veryhardpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=easyapp
      - PMA_PASSWORD=veryhardpassword
    depends_on:
      - database
    restart: always
    ports:
      - 8080:80
     
  application:
    image: easyappointments
    build:
      context: .
    volumes:
      - ./src:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command: dev
    ports:
      - ${APP_HOST}:80:80
    environment:
      - DB_HOST=database:3306
      - APP_URL=localhost
      - PHP_XDEBUG_ENABLED=1
    depends_on:
      - database
    env_file:
      - .env
    restart: always
